name: Build and Release
on:
  push:
    branches: [ main ]
  pull_request:
    type: [ synchronize ]

jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-21.11
        extra_nix_config: |
          trusted-public-keys = jcouyang.cachix.org-1:TsD057OCpomDztwQiONvnXfLnOaGDhOAAB3C8ODLr14= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          substituters = https://jcouyang.cachix.org https://cache.nixos.org/
    - name: tidy
      run: |
        nix-shell --pure --run "go mod tidy"
    - name: test
      run: |
        nix-shell --pure --run "go test ./..."
  publish:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'publish skip') && (github.ref == 'refs/heads/main')"
    needs:
      - test
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-21.11
        extra_nix_config: |
          trusted-public-keys = jcouyang.cachix.org-1:TsD057OCpomDztwQiONvnXfLnOaGDhOAAB3C8ODLr14= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          substituters = https://jcouyang.cachix.org https://cache.nixos.org/
    - name: tag release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        nix-shell --run "./bin/publish.sh"
